Lyrics/lyrics-database

artists/Alaska Highway/Attitudes of a Difficult Mind/Darkness In My Eyes
artists/Alaska Highway/Attitudes of a Difficult Mind/Warmth

Alaska Highway - Attitudes of a Difficult Mind

---

artists/A/Alice In Chains/Jar of Flies/Nutshell

Alice In Chains

---

artists/B/Brian Setzer/Nitro Burnin' Funny Daddy/Sixty Years

Brian Setzer

---

database/P/Perturbator/I Am The Night/Desire
database/P/Perturbator/I Am The Night/Naked Tongues

two songs from the album; taken from the official bandcamp page

Perturbator: I Am The Night

---

database/A/Alaska Highway/Attitudes of a Difficult Mind/Butterfly in a Glass Jar
database/A/Alaska Highway/Attitudes of a Difficult Mind/Hell Bound Heart
database/A/Alaska Highway/Attitudes of a Difficult Mind/Warmth
database/A/Alaska Highway/Closure/Aging
database/A/Alaska Highway/Closure/City Of Angels (Hybrid Mix)
database/A/Alaska Highway/Closure/Event Horizon (Hybrid Mix)
database/A/Alaska Highway/Closure/Skyline
database/A/Alaska Highway/Closure/Uzumaki (Hybrid Mix)
database/A/Alaska Highway/Closure/Winter Within

Some texts are still not complete
I will attempt to contact the artist

Alaska Highway

---

database/M/Massive Attack/Mezzanine/Dissolved Girl
database/M/Massive Attack/Mezzanine/Man Next Door

the texts are correct but a bit hard to read, broken down into smaller logical chunks

prettify Massive Attack

---

database/T/The Electric Hellfire Club/Satan's Little Helpers/Mr. 44

This is quite incomplete but currently all I've managed to dig up. Not exactly a mainstream artist, so should be grateful even for this.

add Mr. 44 by The Electric Hellfire Club

---

database/T/The Twilight Garden/Hope/Hope

I am not so sure about the fourth block from the top, it may be not 100% correct. Need to contact the artist and ask for corrections.

add Hope by The Twilight Garden

---

soundtracks/videogames/N/Need for Speed: Hot Pursuit 2/The Buzzhorn - Ordinary

As a side note: need to come up with a way to improve the directory structure.

add Buzzhorn by The Ordinary

---

database/G/Girls Under Glass/Zyklus/Love is in My World
database/G/Girls Under Glass/Zyklus/Whatever Makes You Happy

Also improves one previously existent text by GUG

add one more song by Girls Under Glass

---

database/L/La Porkoj/Jen
translations/en_US/I/Isaac Watts/Joy to the World!
translations/en_US/L/La Porkoj/Jen

I have the English translation, done by myself, so I added a translations directory, different from the database directory only in that it organizes itself by language, en_US being the only one so far.

Added La Porkoj directory and Jen song.

---

database/B/Breaking Benjamin/Ember/Blood
database/B/Breaking Benjamin/Ember/Close Your Eyes
database/B/Breaking Benjamin/Ember/Down
database/B/Breaking Benjamin/Ember/Feed the Wolf
database/B/Breaking Benjamin/Ember/Psycho
database/B/Breaking Benjamin/Ember/Red Cold River
database/B/Breaking Benjamin/Ember/Save Yourself
database/B/Breaking Benjamin/Ember/The Dark of You
database/B/Breaking Benjamin/Ember/Torn in Two
database/B/Breaking Benjamin/Ember/Tourniquet

This seems like a fun project! So here are some of my fav songs :)

Add songs from  Breaking Benjamin - Ember

---

database/C/Coyote Kisses/Six Shooter/Six Shooter
database/G/Girls Under Glass/Nightmares/When I Think About You
database/W/Wumpscut/Embryodead/Embryodead
tests/database-tests.at
translations/en_US/L/La Porkoj/Jen

add Six Shooter,  add test for runaway spaces and correct them everywhere

---

database/Z/ZSK/Herz Für Die Sache/Antifascista

[ZSK] fix typo in Antifascista

---

database/C/Cypress Hill/Stoned Raiders/Bitter
database/C/Cypress Hill/Stoned Raiders/Catastrophe
database/C/Cypress Hill/Stoned Raiders/L.I.F.E.
database/C/Cypress Hill/Stoned Raiders/Memories
database/C/Cypress Hill/Stoned Raiders/Southland Killers

Get rid of the last few chorus bits in the database

---

database/E/Enzo Darren/Drive/Drive

This one is tricky, no correct lyrics out there, different edits of the song released...
Would love another pair of eyes for a check of everything.

add Drive by Enzo Darren

---

database/S/Skinny Puppy/The Process/Hardest Head

This beauty was transcribed from the official video thanks to it featuring words on screen.
For the most part it should be correct, perhaps the most correct version available on the net.

[Skinny Puppy] add Hardest Head from The Process

---

database/N/Nightstop/Return to Synth City/Answering Machine

and slightly correct the text of Answering Machine

[Nightstop] change the directory's name

---

tests/Makefile
tests/README.md
tests/database-tests.at
tools/remove-ds-store.sh

Add test to check for presence of metadata

---

database/A/Anderson .Paak/Oxnard/Tints
database/A/Anderson .Paak/Oxnard/Tints (feat. Kendrick Lamar)
database/J/JID/The Never Story/NEVER
database/L/Little Simz/GREY Area/Venom

- [Little Simz] add Venom from GREY Area
- [JID] add NEVER from The Never Story
- [Anderson .Paak] add Tints (feat. Kendrick Lamar) from Oxnard

Three new lyrics

---

database/F/Flávio La Barre/French Romance/French Romance

I don't speak French, but managed to scrape lyrics from the comments section on this page, seems legit™ https://soundcloud.com/stratfordct/flavio-la-barre-french-romance
@C0rn3j you will likely enjoy this one

[Flávio La Barre] add French Romance

---

README.md

Update README.md to better describe and legally protect the project

---

database/L/Little Simz/GREY Area/Venom

https://github.com/Lyrics/lyrics/pull/319 (I'm sorry I'm a little late.)

[Little Simz] improve Venom

---

database/B/Boy Harsher/Lesser Man (extended version)/Love

The missing piece after 1:08 was provided by the band, this is the only place on the Internet where that piece is present (not even the back side of the vinyl has it, hence why I had to email them)

[Boy Harsher] correct Love

---

database/P/Paradise Walk/Rogue/Fallen Lovers
database/P/Paradise Walk/Rogue/Machines
database/P/Paradise Walk/Rogue/Rogue
database/P/Paradise Walk/Rogue/Stranger

Minor changes:
- trailing punctuation marks removed to improve readability
- all lines got their first word capitalized

[Paradise Walk] fix 3 texts and add Rogue

---

database/I/Iron Maiden/Killers/Another Life
database/I/Iron Maiden/Killers/Drifter
database/I/Iron Maiden/Killers/Innocent Exile
database/I/Iron Maiden/Killers/Killers
database/I/Iron Maiden/Killers/Murders in the Rue Morgue
database/I/Iron Maiden/Killers/Prodigal Son
database/I/Iron Maiden/Killers/Purgatory
database/I/Iron Maiden/Killers/Twilight Zone
database/I/Iron Maiden/Killers/Wrathchild

I have never done a pull request for a project ever, so i hope i am doing it right.

Add Iron Maiden - Killers

---

database/L/Linkin Park/The Hunting Party/A Line In The Sand
database/L/Linkin Park/The Hunting Party/All For Nothing
database/L/Linkin Park/The Hunting Party/Final Masquerade
database/L/Linkin Park/The Hunting Party/Guilty All The Same
database/L/Linkin Park/The Hunting Party/Keys To The Kingdom
database/L/Linkin Park/The Hunting Party/Mark The Graves
database/L/Linkin Park/The Hunting Party/Rebellion
database/L/Linkin Park/The Hunting Party/Until It's Gone
database/L/Linkin Park/The Hunting Party/War
database/L/Linkin Park/The Hunting Party/Wastelands

Add an album. Thanks for taking time to review this.

Add album The Hunting Party by artist Linkin Park

---

database/L/Linkin Park/One More Light/Battle Symphony
database/L/Linkin Park/One More Light/Good Goodbye
database/L/Linkin Park/One More Light/Halfway Right
database/L/Linkin Park/One More Light/Heavy
database/L/Linkin Park/One More Light/Invisible
database/L/Linkin Park/One More Light/Nobody Can Save Me
database/L/Linkin Park/One More Light/One More Light
database/L/Linkin Park/One More Light/Sharp Edges
database/L/Linkin Park/One More Light/Sorry for Now
database/L/Linkin Park/One More Light/Talking to Myself

The last published studio album of Linkin Park. Wish someday we can add a new one.

Add album One More Light by artist Linkin Park

---

database/L/Linkin Park/A Thousand Suns/Jornada Del Muerto

Replaced with more formal Japanese character, together with pronunciation.
@snshn Is it a good idea to add pronunciation here? I add it because it's a minor language in an English album, and is hard to read.

Update Jornada Del Muerto

---

database/T/Type O Negative/Bloody Kisses/Black No. 1 (Little Miss Scare-All)
database/T/Type O Negative/Bloody Kisses/Blood & Fire
database/T/Type O Negative/Bloody Kisses/Christian Woman
database/T/Type O Negative/Life Is Killing Me/Anesthesia
database/T/Type O Negative/Life Is Killing Me/I Don't Wanna Be Me
database/T/Type O Negative/Life Is Killing Me/Life Is Killing Me
database/T/Type O Negative/Life Is Killing Me/Nettie
database/T/Type O Negative/October Rust/Love You To Death
database/T/Type O Negative/October Rust/My Girlfriend's Girlfriend
database/T/Type O Negative/World Coming Down/Everyone I Love Is Dead

Also apostrophes and ellipses!

[Type O Negative] fix metadata

---

database/J/JK∕47/Future City Dating Service/Chiba City Bar 千叶市律师
database/J/JK∕47/Future City Dating Service/Dethroned 废黜
database/J/JK∕47/Future City Dating Service/Harukiya 遥
database/J/JK∕47/Future City Dating Service/HitSquad 命中小队
database/J/JK∕47/Future City Dating Service/Kaori and Kai かおり あんｄ かい
database/J/JK∕47/Future City Dating Service/Lethal Weapon 凶器
database/J/JK∕47/Future City Dating Service/Lou's Tavern 娄的小酒馆
database/J/JK∕47/Future City Dating Service/Marla 玛拉
database/J/JK∕47/Future City Dating Service/Molly 莫莉
database/J/JK∕47/Future City Dating Service/Nu Nu House 没有没有房子
database/J/JK∕47/Future City Dating Service/Priss 价格
database/J/JK∕47/Future City Dating Service/Sarah 莎拉
database/J/JK∕47/Future City Dating Service/Tech Noir∕ 霓虹鸡尾酒
database/J/JK∕47/Future City Dating Service/The Red King 红王
database/J/JK∕47/Future City Dating Service/Wires Club ワイヤークラブ

`...` need to be filled in, I'll try getting in touch with JK/47 and/or Sam Haine

[JK/47] add album Future City Dating Service

---

database/L/Linkin Park/Meteora/Don't Stay

A small update, for better arrangement. 😃

Update Don't Stay

---

database/L/Linkin Park/The Hunting Party/Mark The Graves

Correct wrong song name

---

database/L/Linkin Park/Living Things/Skin To Bone

😄 Thanks for viewing this. Best wishes!

correct wrong lyrics

---

database/N/Nicole/Butterfly

Song performed by [Nicole (Siebert) Hohloch](https://en.wikipedia.org/wiki/Nicole_(German_singer)).

add lyrics to Butterfly by Nicole

---

database/N/Nicole/Butterfly/Butterfly

There are 4 versions of this song: Papillon performed in German, French, and Dutch. The English version is called "Butterfly".
Laurence's name is an additional credit shown on Butterfly, according to https://charts.nz/showitem.asp?interpret=Nicole&titel=Butterfly&cat=s
In my opinion, it's reasonable to assume he contributed primarily to the English lyrics, because the musical composition of the 4 songs didn't change between the 4 versions (If it did, I can't tell).
For example, you see how the credits differ on the French version:
https://lescharts.com/showitem.asp?interpret=Nicole&titel=Papillon+%5Bfran%E7ais%5D&cat=s
The two other writers listed here wrote the original German lyrics, and should remain, imo, since that's what the English version is based on.

add Zack Laurence to Butterfly credits

---

database/J/JPEGMAFIA/All My Heroes Are Cornballs/All My Heroes Are Cornballs
database/J/JPEGMAFIA/All My Heroes Are Cornballs/BBW
database/J/JPEGMAFIA/All My Heroes Are Cornballs/BUTTERMILK JESUS TYPE BEAT
database/J/JPEGMAFIA/All My Heroes Are Cornballs/BasicBitchTearGas
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Beta Male Strategies
database/J/JPEGMAFIA/All My Heroes Are Cornballs/DOTS FREESTYLE REMIX
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Free The Frail
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Grimy Waifu
database/J/JPEGMAFIA/All My Heroes Are Cornballs/JPEGMAFIA TYPE BEAT
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Jesus Forgive Me, I Am A Thot
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Kenan Vs. Kel
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Lifes Hard, Here’s a Song About Sorrel
database/J/JPEGMAFIA/All My Heroes Are Cornballs/PRONE!
database/J/JPEGMAFIA/All My Heroes Are Cornballs/PTSD
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Papi I Missed U
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Post Verified Lifestyle
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Rap Grow Old & Die x No Child Left Behind
database/J/JPEGMAFIA/All My Heroes Are Cornballs/Thot Tactics

Extended metadata section of All My Heroes Are Cornballs (album) by JPEGMAFIA

[JPEGMAFIA] extend metadata of AMHAC

---

database/M/Macklemore/Drug Dealer/Drug Dealer

Although [MusicBrainz lists this song as by "Macklemore & Ryan Lewis"](https://musicbrainz.org/recording/2ce50bc1-13d2-426a-a4e6-c2c1cd67a29e), Lewis was not included in the official credits.
https://www.youtube.com/watch?v=fYN14UfO-Uc
https://genius.com/Macklemore-drug-dealer-lyrics
>Though he has produced the vast majority of the beats Macklemore has rapped over, Ryan Lewis is not listed among the official song credits for “Drug Dealer,” which can be seen on the [official Soundcloud page for the song](https://soundcloud.com/macklemore/drug-dealer).
I just listed Ben Haggerty as the lyricist, which is shown on the official YouTube video. Most of the lyrics sites only showed a single writing credit, which presumably includes lyrics and musical composition. …

add [Macklemore]Drug Dealer

---

database/A/Adele/25/Hello

For the writing credits, I used info from
https://www.azlyrics.com/lyrics/adele/hello.html
https://www.metrolyrics.com/hello-lyrics-adele.html

[Adele]Hello moved to [album]25, metadata added

---

database/A/Alannah Myles/Alannah Myles/Black Velvet

Also used proper quotation marks, and moved into album

[Alannah Myles] fix typo in Black Velvet

---

database/N/Nicole/Butterfly/Where Have All My Heroes Gone

Missing one line. Can anyone make out the words between 2m:45s and 2m:50s?
https://www.youtube.com/watch?t=165&v=mHOlfcmFizE&feature=youtu.be

[Nicole]add Where Have All My Heroes Gone

---

database/C/Crying Vessel/Necrozine/Destroyed By The Sound
docs/Credits.md

These lyrics are 100% correct as the text was provided by the artist himself.

[Crying Vessel] add lyrics to Destroyed By The Sound

---

docs/Format.md

Information taken from
https://github.com/Lyrics/lyrics/blob/master/tests/database-tests.d/4-metadata.py#L16
(#215) (#228)

add info about available fields, add inline template

---

database/B/Bloodhound Gang/Hefty Fine/Ralph Wiggum
database/C/Curve/Open Day at the Hate Fest/You Don't Know
tests/database-tests.d/1-file-and-directory-structure.py
tests/database-tests.d/2-file-contents.py
tests/database-tests.d/3-song-texts.py
tests/database-tests.d/4-metadata.py
tests/database-tests.py

Also fixes metadata of two lyrics files that it detected to be incorrectly tagged

Introduce two additional tests

---

database/G/Glenn Frey/You Belong to the City/You Belong to the City

on MusicBrainz it states that "A" and "B1" are tracks on that single, but looks like a mistake to me https://musicbrainz.org/release/905ccb57-1100-40fe-a75b-5477293ec2c0

[Glenn Frey] fix track number

---

database/P/Psychopomps/Six Six Six Nights in Hell/Superpsycho

[Psychopomps] add Superpsycho from Six Six Six Nights in Hell

---

database/R/R.A. The Rugged Man/All My Heroes Are Dead/Who Do We Trust
translations/Turkish/R/R.A. The Rugged Man/Who Do We Trust/Who Do We Trust

and Turkish translation of it.

[R.A. The Rugged Man] add Who Do We Trust?

---

database/S/Secret Sign/Night Rituals/Sullenprod

Text donated by one of the band's members
#506

[Secret Sign] add Sullenprod from Night Rituals

---

database/P/Placebo/Sleeping With Ghosts/Bitter End

[Placebo] add Bitter End

---

database/C/Crying Vessel/Necrozine/An Oceans Greed
database/C/Crying Vessel/Necrozine/Carry On
database/C/Crying Vessel/Necrozine/Cosmic (featuring Kim Welsh and Perry Pelonera)
database/C/Crying Vessel/Necrozine/Dreams Of A Ghost Town
database/C/Crying Vessel/Necrozine/Eclipse
database/C/Crying Vessel/Necrozine/Loaded Gun (Featuring Preston Maddox, Kim Welsh and Eriq Johnson)
database/C/Crying Vessel/Necrozine/Something To Me
database/C/Crying Vessel/Necrozine/Take My Hand
database/C/Crying Vessel/Necrozine/The Only Child

Big thanks to Slade Templeton for providing texts and helping the project once again!

[Crying Vessel] add remaining texts from Necrozine

---

database/S/Stone Temple Pilots/Purple/Interstate Love Song

Based on what's inside the official LP (lyrics insert).

[Stone Temple Pilots] fix Interstate Love Song

---

database/Z/Zanias/Unearthed/Unbound
database/Z/Zanias/Unearthed/Undreamt
database/Z/Zanias/Unearthed/Unfathomed
database/Z/Zanias/Unearthed/Unraveled
database/Z/Zanias/Unearthed/Unseen
database/Z/Zanias/Unearthed/Untamed
database/Z/Zanias/Unearthed/Untethered
database/Z/Zanias/Unearthed/Unturned

There's a lyrics booklet that comes with the CD, but I bought my copy of the album via bandcamp, so besides what Alison shared with fans on Patreon, I have nothing to use as a source.  I'll reach out to the artist in a bit to help with all lyrics that she wrote for all of her projects including this album.

[Zanias] add texts from Unearthed

---

database/A/Anthony Rother/Sex With the Machines/Describe Reality

Not sure what the robo voice says, will add later

[Anthony Rother] add Describe Reality

---

database/D/Dave Vanian and The Phantom Chords/The Unreleased Album/Haunted Garage

[Dave Vanian and The Phantom Chords] move Haunted Garage under different artist

---

database/G/George Thorogood And The Destroyers/Maverick/I Drink Alone

@defanor since I'm not an alcoholic myself, need some help making sure everything is okay here... could you please give it a glance?

[George Thorogood And The Destroyers] add I Drink Alone

---

.github/workflows/cd.yml

Update GitHub CD action for changes in website generator

---

database/S/Stereotaxic Device/Stereotaxic Device/Lostland

Alternative version, just for the record:
```
Kaleidoscopes are celebrating,
Windows have wings,
The suicide, the genocide of the Indians, Indians.
The signals from Heaven,
Are like a sea of flames,
The suicide, the genocide of the Indians, Indians.
I’ve forgotten all traces of,
Yesterday, yesterday.
The suicide, the genocide of the Indians, Indian.
Kaleidoscopes are celebrating,
Windows have wings,
The genocide, the suicide of the Indians, American Indian.
```

[Stereotaxic Device] add Lostland

---

database/Y/Yung Gravy/Marvelous/C'est La Vie

Added C'est La Vie by Yung Gravy

[Yung Gravy] add C'est La Vie

---

database/M/Mussolini Headkick/Themes for Violent Retribution/Jesus Collects

Transcribed mostly by what's on the back of the LP.
Still missing some parts, will patch up later.

add Jesus Collects by Mussolini Headkick

---

database/F/Freaks of Desire/Unknown Album/Unknown Song

https://www.youtube.com/watch?v=67U8i3Ifk5U
Need to get their recordings to figure out what song it is, or ask that YouTube channel's owner

Add unknown song by Freaks of Desire

---

database/C/Curve/Horror Head/Falling Free
database/C/Curve/Rare and Unreleased/Worst Mistake

I'll reach out to Toni Halliday and ask for Falling Free text; not available on the web (same as with Sigh from Rare and Unreleased).

More Curve

---

database/P/Paul Saax/Jack's Back Soundtrack/Red Harvest (Version 1)
database/P/Paul Saax/Jack's Back Soundtrack/Red Harvest (Version 2)

This is a tough one, since no official soundtrack was ever released, and there're two versions of the same song.  Might have to rename/move it later, but that's alright.

Add two texts of Red Harvest by Paul Saax

---

tests/database-tests.d/4-metadata.py

The new search mechanism will be modified to detect artist/album/song names from the path.

Do not check for metadata to be present
